# Setup
title:            Matthias Mullie
tagline:          'Software engineer'
description:      'Matthias Mullie, software engineer'
url:              https://www.mullie.eu
baseurl:          /
image:            public/logo_300.png
enforce_ssl:      www.mullie.eu

author:
  name:           'Matthias Mullie'
  gplus:          https://plus.google.com/u/0/114103174273569238978
  twitter:        matthiasmullie

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/matthiasmullie/matthiasmullie.github.io

permalink:        /:title/

gems:
  # Generate sitemap
  - jekyll-sitemap

# Titles of posts to be displayed in "top posts" widget
top_posts:       ["Regular expressions for pros", "Async processing or multitasking in PHP", "How to build a MySQL-powered search engine"]
